[package]
name = "hiivelabs_chunk_lib"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hiivelabs_storage_lib = { version = "0.1.0", path = "../hiivelabs_storage_lib" }
hiivelabs_rand_utils_lib = { version = "0.1.0", path = "../hiivelabs_rand_utils_lib" }

smallvec = { version = "2.0.0-alpha.7" }
# hecs = "0.10.5"
rand = { version = "0.9.0-alpha.2" }
schnellru = "0.2.3"
bitcode = { version = "0.6.3" }
miniz_oxide = "0.8.0"
uuid = { version = "1.10.0", features = ["v4"] }
blake2 = { version = "0.11.0-pre.4" }
rand_core = "0.9.0-alpha.2"
log = "0.4.22"
indexmap = { version = "2.2.6", features = [] }
num_cpus = "1.16.0"
rustc-hash = "2.0.0"


[features]
# multithreaded_chunk_generation = []
# default=["multithreaded_chunk_generation"]

